=== Naohiro2g/scratchClient/config/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mcp23s17="mcp23s17.xsd">
	<xs:import namespace="mcp23s17.xsd" schemaLocation="mcp23s17.xsd" />
	<xs:complexType name="gpio_type">
		<xs:sequence>
			<xs:element name="default" type="io_type"></xs:element>
			<xs:element name="active" type="io_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="port" type="xs:string"></xs:attribute>
		<xs:attribute name="alias" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="input_type">
		<xs:sequence>
			<xs:element name="broadcast" type="named_type" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="output_type">
		<xs:sequence>
			<xs:element name="broadcast" type="named_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="input_value_type">
		<xs:sequence>
			<xs:element name="variable" type="named_type" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="output_value_type">
		<xs:sequence>
			<xs:element name="sensor" type="named_type" minOccurs="0"></xs:element>

		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="parameter_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="route_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="route" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="html_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="path" type="xs:string"></xs:attribute>
		<xs:attribute name="comment" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="webserver_type">
		<xs:sequence>
			<xs:element name="route" type="route_type"></xs:element>
			<xs:element name="html" type="html_type" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="adapter_MCP23S17_type">
		<xs:complexContent>
			<xs:extension base="adapter_type">
				<xs:sequence>

					<xs:element name="io" type="mcp23s17:io_type" maxOccurs="unbounded" minOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="adapter_type">
		<xs:sequence>
			<xs:element name="description" type="xs:string" maxOccurs="1" minOccurs="0" />
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="gpio" type="gpio_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="input" type="input_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="input_value" type="input_value_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="output" type="output_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="output_value" type="output_value_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="parameter" type="parameter_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="webserver" type="webserver_type" maxOccurs="1" minOccurs="0">
				</xs:element>

			</xs:choice>
		</xs:sequence>

		<xs:attribute name="class" type="xs:string"></xs:attribute>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>


	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string" />

				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="adapter" type="adapter_type" />
					<xs:element name="adapter_MCP23S17" type="adapter_MCP23S17_type" />
				</xs:choice>

			</xs:sequence>
			<xs:attribute name="version" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>


	<xs:complexType name="io_type">
		<xs:attribute name="dir" type="iodirection_type"></xs:attribute>
		<xs:attribute name="pull" type="pullup_type"></xs:attribute>
		<xs:attribute name="default" type="default_type"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="iodirection_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="IN"></xs:enumeration>
			<xs:enumeration value="OUT"></xs:enumeration>
			<xs:enumeration value="RESERVED"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="pullup_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PUD_OFF"></xs:enumeration>
			<xs:enumeration value="PUD_UP"></xs:enumeration>
			<xs:enumeration value="PUD_DOWN"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="named_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="default_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="low"></xs:enumeration>
			<xs:enumeration value="high"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Naohiro2g/scratchClient/config/config_adc_atmel328.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="config.xsd" >
    <!--
    # ===========================================================================
    # Copyright (C) 2014  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # ===========================================================================
    -->
    <description>ADC-Values from an Atmel atmega328, 8MHz with program 'steckbrett_328.hex'.
        Output values are 0..1023, relative to VCC.
        Reads frequency measurements.</description>

    <!-- =========================================================================== -->
    <adapter class='adapter.atmel328_adapter.Atmel328_ADC_Adapter'  name='adc_328'>
        
        <description>ADC-Values and a LED</description>
        
        <output_value name='analog_0'>
            <sensor name='adc_A0'/>
        </output_value>
        
        <output_value name='analog_1'>
            <sensor name='adc_A1'/>
        </output_value>

        <output_value name='timer'>
            <sensor name='freq'/>
        </output_value>
               
        <input name= 'led_on'>
            <broadcast name='led_on'/>
        </input>   
           
        <input name= 'led_off'>
            <broadcast name='led_off'/>
        </input>
        
        <!-- although not actively used, this is needed to handle reset line -->
        <gpio port='GPIO24'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='high' />
        </gpio>

        <!-- polling time for external device -->
        <parameter name='poll.interval' value='0.05' />

        <!-- enable timer on atmel firmware 
             values 0, 1 -->
        <parameter name='timer.enable' value='1' />
        <!-- enable noise cancelling for ICP1== PB.1 on atmel firmware 
             limits input range, but generally a good idea to enable this. 
             values 0, 1 -->
        <parameter name='timer.noisecanceller' value='1' />
 
        <parameter name='adc.0.enable' value='0' />
        <parameter name='adc.1.enable' value='1' />
        
        <!-- avcc = 3.3V , internal == 1.1V -->
        <parameter name='adc.0.reference' value='internal' />
        <parameter name='adc.1.reference' value='internal' />

 
        <parameter name='spi.bus' value='0' />
        <parameter name='spi.device' value='0' />
    </adapter>

</config>

=== Naohiro2g/scratchClient/config/config_ikg_drehencoder.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2013  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->
	<description>
		Encoder with two photointerruptors in gl.4, gl.5 GPIO25, 24. --> position_A
		Encoder with two photointerruptors in gl.6, gl.7 GPIO17, 15. --> position_B
		
		Pullup are needed, as provided on IKG-Adapter.
		With N=6 'teeth', the resolution is 30 degree.

		Jumper: 
			gesetzt:
               in.4 bis in.7 
            offen:
			   out.0 bis out.7
               out2.0 bis out2.7 

	</description>

	<!-- =========================================================================== -->
	<adapter class='adapter.encoder.GPIOEncoder'  name='encoder_A'>
		<description>Drehencoder</description>

		<gpio port='IKG.IO.4' alias='p0'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'   />
		</gpio>
		<gpio port='IKG.IO.5' alias='p1'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'   />
		</gpio>

		<output_value name='position'>
			<sensor name='positionA'/>
		</output_value>

		<parameter name='poll.interval' value='0.005' />

	</adapter>

	<adapter class='adapter.encoder.GPIOEncoder'  name='encoder_B'>
		<description>Drehencoder</description>

		<gpio port='IKG.IO.6' alias='p0'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'   />
		</gpio>
		<gpio port='IKG.IO.7' alias='p1'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'   />
		</gpio>

		<output_value name='position'>
			<sensor name='positionB'/>
		</output_value>

		<parameter name='poll.interval' value='0.005' />

	</adapter>

    <adapter class='adapter.gpio.GpioStateOutput'  name='state'>
        <description>State display on IKG.IO.9</description>

        <gpio port='IKG.IO.9' alias='state'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='low' />
        </gpio>
    </adapter>

</config>

=== Naohiro2g/scratchClient/config/config_barcode.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2013  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->

	<description>Sample configuration for barcode scanner</description>

	<!-- =========================================================================== -->
	
	<adapter class='adapter.usbAdapter.HIDScanner_Adapter' name='barcode scanner'>
		
		<description>Provides scan results from a barcode scanner.</description>

		<output_value name='scan'>
            <sensor name='barcode'/>
        </output_value>

        <parameter name="usb.idVendor"  value="0x0c2e"  />
        <parameter name="usb.idProduct" value="0x0200"  />

	</adapter>

</config>

=== Naohiro2g/scratchClient/config/config_stepper_28BYJ-48_step.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2013  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->

	<description>
	    Stepper configuration. Unipolar Stepper, connected with a ULN2803 darlington driver.
	    Switch input on IKG.IO.4 (microswitch for position detect, inverted)
	</description>

	<!-- =========================================================================== -->
	
	<adapter class='adapter.stepper.UnipolarStepperStep' name='stepper'>
		
		<description>stepper control for unipolar stepper
		Allows for discrete switch signals br0.0, br0.1, br1.0, br1.1
		or binary inputs 'pattern', e.g b0001, b0011, ...
        

		</description>
		
        <gpio port='IKG.IO.0' alias='br0.0'>
            <default dir='OUT' pull='PUD_OFF' default='low'  />
            <active dir='OUT' pull='PUD_OFF'/>
        </gpio>
        <gpio port='IKG.IO.1' alias='br0.1'>
            <default dir='OUT' pull='PUD_OFF' default='low' />
            <active dir='OUT' pull='PUD_OFF'/>
        </gpio>
        
        <gpio port='IKG.IO.2' alias='br1.0'>
            <default dir='OUT' pull='PUD_OFF' default='low' />
            <active dir='OUT' pull='PUD_OFF'/>
        </gpio>
        <gpio port='IKG.IO.3' alias='br1.1'>
            <default dir='OUT' pull='PUD_OFF' default='low' />
            <active dir='OUT' pull='PUD_OFF'/>
        </gpio>

        <input_value name='br0_0'>
            <variable name='br0.0'/>
        </input_value>
        <input_value name='br0_1'>
            <variable name='br0.1'/>
        </input_value>
        <input_value name='br1_0'>
            <variable name='br1.0'/>
        </input_value>
        <input_value name='br1_1'>
            <variable name='br1.1'/>
        </input_value>
        
        <input_value name='binaryPattern'>
            <variable name='pattern'/>
        </input_value>
        
	</adapter>

   <!-- =========================================================================== -->

    <adapter class='adapter.gpio.GpioInput' name='microschalter'>
        <!-- no description, urgg -->
        <gpio port='IKG.IO.4'>
            <default dir='IN' pull='PUD_UP'  />
            <active dir='IN' pull='PUD_UP'/>
        </gpio>
        <output_value name='button'>
            <sensor name='microschalter'/>
        </output_value>
        <parameter name='poll.interval' value='0.05' />
        <parameter name='value.inverse' value='true' />
    </adapter>

   <!-- =========================================================================== -->
	
    <adapter class='adapter.gpio.GpioStateOutput'  name='state'>
        <description>State display on IKG.IO.9</description>

        <gpio port='IKG.IO.9' alias='state'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='low' />
        </gpio>
    </adapter>
 
</config>

=== Naohiro2g/scratchClient/config/config_ikg_irdistance.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2013  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->
	<description>
		IR-Distance-Sensor on ADC.0
		Linearization based on Sharp datasheet.
		Output values are distance in [mm].
	</description>

	<!-- =========================================================================== -->
    <adapter class='adapter.adc.IRDistanceInput'  name='irDistanceA'>
        <description>IR-Distance Sensor</description>

        <output_value name='distance'>
            <sensor name='distanceA'/>
        </output_value>

        <parameter name='poll.interval' value='0.066' />
        <parameter name='spi.bus' value='0' />
        <parameter name='spi.device' value='0' />
        <parameter name='adc.channel' value='0' />
        <parameter name='filter.use' value='true' />
        <parameter name='filter.depth' value='5' />

    </adapter>
    <adapter class='adapter.adc.IRDistanceInput'  name='irDistanceB'>
        <description>IR-Distance Sensor</description>

        <output_value name='distance'>
            <sensor name='distanceB'/>
        </output_value>

        <parameter name='poll.interval' value='0.066' />
        <parameter name='spi.bus' value='0' />
        <parameter name='spi.device' value='0' />
        <parameter name='adc.channel' value='1' />
        <parameter name='filter.use' value='true' />
        <parameter name='filter.depth' value='5' />

    </adapter>
	<!-- =========================================================================== -->
	<adapter class='adapter.gpio.GpioEventInput' name='button_s0'>
		<!-- no description, urgg -->
		<gpio port='GPIO25'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'/>
		</gpio>
		
		<output name='button_pressed'>
			<broadcast name='s0_pressed'/>
		</output>
		<output name='button_released'>
			<broadcast name='s0_released'/>
		</output>
		
		<parameter name='poll.interval' value='0.075' />
        <parameter name='value.inverse' value='true' />
	</adapter>
	
	<adapter class='adapter.gpio.GpioEventInput' name='button_s1'>
		<!-- no description, urgg -->
		<gpio port='GPIO24'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'/>
		</gpio>
		
		<output name='button_pressed'>
			<broadcast name='s1_pressed'/>
		</output>
		<output name='button_released'>
			<broadcast name='s1_released'/>
		</output>
		
		<parameter name='poll.interval' value='0.075' />
		      <parameter name='value.inverse' value='true' />

	</adapter>
	
    <adapter class='adapter.gpio.GpioStateOutput'  name='state'>
        <description>State display on IKG.IO.9</description>

        <gpio port='IKG.IO.9' alias='state'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='low' />
        </gpio>
    </adapter>

</config>

=== Naohiro2g/scratchClient/scratch/neopixel/neopixel.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mcp23s17="mcp23s17.xsd" xsi:noNamespaceSchemaLocation="config.xsd"
    xsi:schemaLocation="mcp23s17 mcp23s17.xsd "
>

    <!-- 
    # =============================================================================================
    # Copyright (C) 2015  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # =============================================================================================
        -->

    <description>
        Arduino UNO with custom program used to drive neopixel. 
        Needs arduino code arduino/arduinoNeopixel/arduinoNeopixel.ino in arduino UNO/Nano.
    </description>

    <!-- =========================================================================== -->
    <adapter class='adapter.arduino.NEOPIXEL_Adapter' name='UNO_NEOPIXEL'>
        <!--  Sample arduino communication. Needs arduino sketch programmed in arduino. -->

       
        <!-- digital input values are inputs for the adapter (but outputs for arduino) -->
        
        <input_value name='led'>
            <variable name='led'/>
        </input_value>
        
        <input name='clear'>
            <broadcast name='clear'/>
        </input>

        <input name='red'>
            <broadcast name='red_all'/>
        </input>
        <input name='green'>
            <broadcast name='green_all'/>
        </input>
        <input name='blue'>
            <broadcast name='blue_all'/>
        </input>

        <!-- ==================================================== -->
        <!--  on windows, use COMn, e.g. COM6  -->
        <!--  on raspberry, use /dev/ttyn, e.g. /dev/ttyAMA0  -->
         
        <!--  <parameter name='serial.device' value='/dev/ttyUSB0' />
         -->
        
        <parameter name='led.length' value='144' />
        
        <!-- shadow keeps a duplicate of led values in memory and only sends set-led if values
             have changed. This reduces communication effort to arduino and improves
             sppe.  -->
        <parameter name='led.shadow' value='true' />
        
        <parameter name='serial.device' value='COM19' />
        <parameter name='serial.baud' value='115200' />

        <!-- ==================================================== -->
        

    </adapter>

</config>

=== Naohiro2g/scratchClient/config/config_pressure_bmp085.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="config.xsd" >
    <!--
    # ===========================================================================
    # Copyright (C) 2014  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # ===========================================================================
    -->
    <description>Air pressure and temparature.</description>

    <!-- =========================================================================== -->
    <adapter class='adapter.i2cAdapter.Pressure_BMP085_Input'  name='pressure'>
        <description>Pressure-Value from BMP085
        Connected to I2C-Bus.
        </description>
        
        <output_value name='pressure'>
            <sensor name='pressure'/>
        </output_value>

        <output_value name='temperature'>
            <sensor name='temperature'/>
        </output_value>
        
        <parameter name='poll.interval' value='2.5' />
       
        <!-- bus is '1' for RPi Release 2 -->
        <parameter name='i2c.bus' value='1' />
        
        <!-- Depending on address select, the bus address is 
             '0x77' for BMP085 
             
             -->
        <parameter name='i2c.address' value='0x77' />
    </adapter>

</config>
