=== Naohiro2g/scratchClient/config/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mcp23s17="mcp23s17.xsd">
	<xs:import namespace="mcp23s17.xsd" schemaLocation="mcp23s17.xsd" />
	<xs:complexType name="gpio_type">
		<xs:sequence>
			<xs:element name="default" type="io_type"></xs:element>
			<xs:element name="active" type="io_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="port" type="xs:string"></xs:attribute>
		<xs:attribute name="alias" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="input_type">
		<xs:sequence>
			<xs:element name="broadcast" type="named_type" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="output_type">
		<xs:sequence>
			<xs:element name="broadcast" type="named_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="input_value_type">
		<xs:sequence>
			<xs:element name="variable" type="named_type" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="output_value_type">
		<xs:sequence>
			<xs:element name="sensor" type="named_type" minOccurs="0"></xs:element>

		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="parameter_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="route_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="route" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="html_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="path" type="xs:string"></xs:attribute>
		<xs:attribute name="comment" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="webserver_type">
		<xs:sequence>
			<xs:element name="route" type="route_type"></xs:element>
			<xs:element name="html" type="html_type" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="adapter_MCP23S17_type">
		<xs:complexContent>
			<xs:extension base="adapter_type">
				<xs:sequence>

					<xs:element name="io" type="mcp23s17:io_type" maxOccurs="unbounded" minOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="adapter_type">
		<xs:sequence>
			<xs:element name="description" type="xs:string" maxOccurs="1" minOccurs="0" />
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="gpio" type="gpio_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="input" type="input_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="input_value" type="input_value_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="output" type="output_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="output_value" type="output_value_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="parameter" type="parameter_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="webserver" type="webserver_type" maxOccurs="1" minOccurs="0">
				</xs:element>

			</xs:choice>
		</xs:sequence>

		<xs:attribute name="class" type="xs:string"></xs:attribute>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>


	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string" />

				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="adapter" type="adapter_type" />
					<xs:element name="adapter_MCP23S17" type="adapter_MCP23S17_type" />
				</xs:choice>

			</xs:sequence>
			<xs:attribute name="version" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>


	<xs:complexType name="io_type">
		<xs:attribute name="dir" type="iodirection_type"></xs:attribute>
		<xs:attribute name="pull" type="pullup_type"></xs:attribute>
		<xs:attribute name="default" type="default_type"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="iodirection_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="IN"></xs:enumeration>
			<xs:enumeration value="OUT"></xs:enumeration>
			<xs:enumeration value="RESERVED"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="pullup_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PUD_OFF"></xs:enumeration>
			<xs:enumeration value="PUD_UP"></xs:enumeration>
			<xs:enumeration value="PUD_DOWN"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="named_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="default_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="low"></xs:enumeration>
			<xs:enumeration value="high"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Naohiro2g/scratchClient/config/config_ikg_adc_tmp36.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="config.xsd" >
    <!--
    # ===========================================================================
    # Copyright (C) 2013  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # ===========================================================================
    -->
    <description>ADC-Values, 12 Bit resolution.
        Output values are 0..4095.
        A filter is provided. Filter depth configurable.</description>

    <!-- =========================================================================== -->
    <adapter class='adapter.adc.ADC_MCP3202_12_Input'  name='adc_A'>
        
        <description>ADC-Value</description>
        
        <output_value name='adc'>
            <sensor name='adcA'/>
        </output_value>
        
        <parameter name='filter.depth' value='8' />

        <parameter name='poll.interval' value='0.066' />
        <parameter name='spi.bus' value='0' />
        <parameter name='spi.device' value='0' />
        <parameter name='adc.channel' value='0' />
    </adapter>
    <!-- 
    <adapter class='adapter.adc.ADC_MCP3202_12_Input'  name='adc_B'>
        
        <description>ADC-Value</description>
        
        <output_value name='adc'>
            <sensor name='adcB'/>
        </output_value>
        
        <parameter name='filter.depth' value='8' />

        <parameter name='poll.interval' value='0.066' />
        <parameter name='spi.bus' value='0' />
        <parameter name='spi.device' value='0' />
        <parameter name='adc.channel' value='1' />

    </adapter>
     -->
    <!-- =========================================================================== -->
    <adapter class='adapter.gpio.GpioEventInput' name='button_s0'>
        <!-- no description, urgg -->
        <gpio port='GPIO25'>
            <default dir='IN' pull='PUD_UP'  />
            <active dir='IN' pull='PUD_UP'/>
        </gpio>
        
        <output name='button_pressed'>
            <broadcast name='s0_pressed'/>
        </output>
        <output name='button_released'>
            <broadcast name='s0_released'/>
        </output>
        
        <parameter name='poll.interval' value='0.066' />
        <parameter name='value.inverse' value='true' />

    </adapter>

    <adapter class='adapter.gpio.GpioOutput'  name='resistor power'>
        <description>power1, to control a resistor as heating element
        </description>

        <gpio port='GPIO24'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='low' />
        </gpio>
        <input name='low'>
            <broadcast name='power1_OFF'/>
        </input>
        <input name='high'>
            <broadcast name='power1_ON'/>
        </input>
        <parameter name='frequency' value='10' />
        <parameter name='rate' value='50' />
        
    </adapter>

    <!-- =========================================================================== -->

    <adapter class='adapter.gpio.GpioStateOutput'  name='state'>
        <description>State display on IKG.IO.9</description>

        <gpio port='IKG.IO.9' alias='state'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='low' />
        </gpio>
    </adapter>
 
</config>

=== Naohiro2g/scratchClient/config/config_dma_servo.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2017  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->
	<description>
	</description>

	<!-- =========================================================================== -->
    <adapter class='adapter.dma_pwm.DMA_PWMServo'  name='servo_pwm'>
        <description>Sample DMA PWM, needs installation of RPIO2-package.</description>

        <gpio port='GPIO23'>
            <default dir='OUT'  default='high' />
            <active dir='RESERVED' />
        </gpio>

        <input_value name='rate'>
            <variable name='servo_A'/>
        </input_value>

        <parameter name='frequency' value='50' />
        <parameter name='rate' value='50' />
 
        <!--  optional parameter -->
        <parameter name='value.inverse' value='true' />
        
        
        <!--  millisecond min is 0.5 [ms] minimum, default = 1 [ms] -->
        <!--  millisecond max is 1.5 [ms] minimum, default = 2 [ms] -->
        <parameter name="millisecond.min" value="1.0" />
        <parameter name="millisecond.max" value="2.0" />
    </adapter>

</config>

=== Naohiro2g/scratchClient/config/config_ikg_servo2.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2015  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->
	<description>
		Servo control.
		Input values are servo_A. 
		Values 0..100.
		
		Buttons s0, s1, s8 are active.
		Output events are 's0_pressed', 's1_pressed', 's8_pressed'.
		Output events are 's0_released', 's1_released', 's8_released' fuer scratch bezeichnet.

		Jumper: 
			gesetzt:
               out.2
               out2.2
               jp3.0 
            offen:
			   out.0, 1, out.3 bis out.7
               in.0 bis in.7 

		
	</description>

	<!-- =========================================================================== -->
	<adapter class='adapter.dma_pwm.DMA_PWMServo'  name='servo_pwm'>
		<description>Sample DMA PWM, needs installation of RPIO2-package.</description>

		<gpio port='GPIO23'>
			<default dir='OUT'  default='high' />
			<active dir='RESERVED' />
		</gpio>

		<input_value name='rate'>
			<variable name='servo_A'/>
		</input_value>

		<parameter name='frequency' value='50' />
		<parameter name='rate' value='50' />
        <parameter name='value.inverse' value='true' />
        
        <!--  optional parameter -->
        
        <!--  millisecond min is 0.5 [ms] minimum, default = 1 [ms] -->
        <!--  millisecond max is 1.5 [ms] minimum, default = 2 [ms] -->
        <parameter name="millisecond.min" value="1.0" />
        <parameter name="millisecond.max" value="2.0" />
	</adapter>

	<adapter class='adapter.gpio.GpioEventInput' name='button_s0'>
		<!-- no description, urgg -->
		<gpio port='GPIO25'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'/>
		</gpio>
		
		<output name='button_pressed'>
			<broadcast name='s0_pressed'/>
		</output>
		<output name='button_released'>
			<broadcast name='s0_released'/>
		</output>
		
		<parameter name='poll.interval' value='0.05' />
        <parameter name='value.inverse' value='true' />
	</adapter>
	
	<adapter class='adapter.gpio.GpioEventInput' name='button_s1'>
		<!-- no description, urgg -->
		<gpio port='GPIO24'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'/>
		</gpio>
		
		<output name='button_pressed'>
			<broadcast name='s1_pressed'/>
		</output>
		<output name='button_released'>
			<broadcast name='s1_released'/>
		</output>
		
		<parameter name='poll.interval' value='0.05' />
        <parameter name='value.inverse' value='true'/>
	</adapter>

	<adapter class='adapter.gpio.GpioEventInput' name='button_s8'>
		<!-- no description, urgg -->
		<gpio port='GPIO14'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'/>
		</gpio>

		<output name='button_pressed'>
			<broadcast name='s8_pressed'/>
		</output>
		<output name='button_released'>
			<broadcast name='s8_released'/>
		</output>
		
		<parameter name='poll.interval' value='0.05' />
        <parameter name='value.inverse' value='true' />
	</adapter>

    <adapter class='adapter.gpio.GpioStateOutput'  name='state'>
        <description>State display on IKG.IO.9</description>

        <gpio port='IKG.IO.9' alias='state'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='low' />
        </gpio>
    </adapter>

</config>

=== Naohiro2g/scratchClient/config/config_dht22_atmel328.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="config.xsd" >
    <!--
    # ===========================================================================
    # Copyright (C) 2014  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # ===========================================================================
    -->
    <description>Temperature in degree Celsius; Humidity in Percent.</description>

    <!-- =========================================================================== -->
    <adapter class='adapter.atmel328_adapter.Atmel328_DHT22_Adapter'  name='dht22'>
        
        <description>dht22</description>
        
        <output_value name='humidity'>
            <sensor name='humidity_A'/>
        </output_value>
        
        <output_value name='temperature'>
            <sensor name='temperature_A'/>
        </output_value>
        
        <input name= 'led_on'>
            <broadcast name='led_on'/>
        </input>   
           
        <input name= 'led_off'>
            <broadcast name='led_off'/>
        </input>
        
        <!-- although not actively used, this is needed to handle reset line -->
        <gpio port='GPIO24'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='high' />
        </gpio>

        <!-- polling time for external device -->
        <parameter name='poll.interval' value='5.0' />
        
        <!-- DHT22, DHT11  -->
        <parameter name='sensor.device' value='DHT22' />

       
        <parameter name='spi.bus' value='0' />
        <parameter name='spi.device' value='0' />
    </adapter>

</config>

=== Naohiro2g/scratchClient/config/config_wedo2_basic.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
    <!--
    # ===========================================================================
    # Copyright (C) 2016  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # ===========================================================================
    -->
	<description>
		WEDO 2 by bluetooth
		This file contains 'not strict'-definitions.
		
		
	</description>

	<!-- =========================================================================== -->
	<adapter class='adapter.wedo2Adapter.Wedo2Adapter' name='wedo2'>
		<description>WEDO 2 by bluetooth</description>

		<!-- ===== ==================================== -->
		<!-- MOTOR ==================================== -->

		<input_value name='motor'>
			<variable name='motor' />
		</input_value>
		
		<input name='motor_run'>
			<broadcast name='motor_run' />
		</input>
		<input name='motor_brake'>
			<broadcast name='motor_brake' />
		</input>
		<input name='motor_drift'>
			<broadcast name='motor_drift' />
		</input>


		<!-- ===== ==================================== -->
		<!-- MOTION ==================================== -->
		<!-- ===== ==================================== -->
        
		<output_value name='motion_distance'>
			<sensor name='motion_distance' />
		</output_value>


		<!-- ===== ==================================== -->
		<!-- TILT ==================================== -->
		<!-- ===== ==================================== -->
		

		<output_value name='tilt_tilt'>
			<sensor name='tilt_tilt' />
		</output_value>


		<!-- ===== ==================================== -->
		<!-- RGB ==================================== -->
		<!-- ===== ==================================== -->
		<input_value name='color'>
			<variable name='color' />
		</input_value>

        <!-- ===== ==================================== -->
        <!-- DEVICE ==================================== -->
        <!-- ===== ==================================== -->

		<output name='button_pressed'>
			<broadcast name='button_pressed' />
		</output>
		<output name='button_released'>
			<broadcast name='button_released' />
		</output>

		<output name='low_voltage_alert'>
			<broadcast name='notify_low_voltage_alert' />
		</output>

		<output name='high_current_alert'>
			<broadcast name='notify_high_current_alert' />
		</output>


		<!-- discover option, either by 'name' (needs root permission) -->
		<!-- or connect by 'address' -->
		<parameter name='btle.policy' value='name' />

		<parameter name='btle.name' value='LPF2 Smart Hub 2 I/O' />
		<parameter name='btle.address' value='a0:e6:f8:6d:0e:67' />

		<parameter name='mode.strict' value='false' />

	</adapter>

</config>

=== Naohiro2g/scratchClient/config/config_servoblaster.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2015  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->

	<description>
		Sample implementation for connecting to servoblaster.
		Start servoblaster first !
    </description>
    
	<!-- =========================================================================== -->
	<adapter class='adapter.servoblaster.ServoBlaster'  name='servoblaster'>
		<description>servoblaster for 8 channels. See servoblaster doku for 
		assignment of channel index numbers to GPIO pins.</description>

		
		<!--  looks strange, but could do some renaming for scratch variables here  -->
        <input_value name= 'servo_0'>
            <variable name='servo_0'/>
        </input_value>
        <input_value name= 'servo_1'>
            <variable name='servo_1'/>
        </input_value>
        <input_value name= 'servo_2'>
            <variable name='servo_2'/>
        </input_value>
        <input_value name= 'servo_3'>
            <variable name='servo_3'/>
        </input_value>
        <input_value name= 'servo_4'>
            <variable name='servo_4'/>
        </input_value>
        <input_value name= 'servo_5'>
            <variable name='servo_5'/>
        </input_value>
        <input_value name= 'servo_6'>
            <variable name='servo_6'/>
        </input_value>
        <input_value name= 'servo_7'>
            <variable name='servo_7'/>
        </input_value>
	</adapter>

</config>

=== Naohiro2g/scratchClient/config/config_telefonwaehlscheibe.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2013  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->
	<description>
		Dial Plate with two contacts
		   nsa: closed during dial plate movements
		   nsi: pulse contact
		
		Pullup are needed, as provided on IKG-Adapter.
		With N=6 'teeth', the resolution is 30 degree.

		Jumper: 
			gesetzt:
               in.0 bis in.7 
            offen:
			   out.0 bis out.7
               out2.0 bis out2.7 

	</description>

	<!-- =========================================================================== -->
	<adapter class='adapter.encoder.GPIODialPlateEncoder'  name='dial_A'>
		<description>Wè¾°hlscheibe.
		Anschluss: NSI (Impuls) 
		           NSA (Drehschalter)
		</description>

		<gpio port='IKG.IO.1' alias='nsi'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'   />
		</gpio>
		<gpio port='IKG.IO.3' alias='nsa'>
			<default dir='IN' pull='PUD_UP'  />
			<active dir='IN' pull='PUD_UP'   />
		</gpio>

		<output_value name='number'>
			<sensor name='numberA'/>
		</output_value>
		
	</adapter>

</config>

=== Naohiro2g/scratchClient/config/config_hcsr04_pigpiod.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2015  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->
	<description>
		HC-SR04 controlled by pigpiod
		pigpiod must be started; the code does not start it automatically 
	</description>

	<!-- =========================================================================== -->
	<adapter class='adapter.pigpiodAdapter.HC_SR04_Adapter'  name='echo-time'>
		<description>HC-SR04 controller</description>

        <!--  gpio are not used directly. Set 'dir' to 'RESERVED'. -->
        
        <gpio port='GPIO18'   alias='trigger'>
            <default dir='RESERVED' />
            <active dir='RESERVED' />
        </gpio>
        <gpio port='GPIO23' alias='echo'>
            <default dir='RESERVED' />
            <active dir='RESERVED' />
        </gpio>

        <output_value name='time'>
            <sensor name='time'/>
        </output_value>

        <output_value name='error'>
            <sensor name='error'/>
        </output_value>

         <!--  minimal value 0.02 -->
		 <parameter name='poll.interval' value='0.5' />
	</adapter>
</config>
