=== Naohiro2g/scratchClient/config/config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mcp23s17="mcp23s17.xsd">
	<xs:import namespace="mcp23s17.xsd" schemaLocation="mcp23s17.xsd" />
	<xs:complexType name="gpio_type">
		<xs:sequence>
			<xs:element name="default" type="io_type"></xs:element>
			<xs:element name="active" type="io_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="port" type="xs:string"></xs:attribute>
		<xs:attribute name="alias" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="input_type">
		<xs:sequence>
			<xs:element name="broadcast" type="named_type" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="output_type">
		<xs:sequence>
			<xs:element name="broadcast" type="named_type"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="input_value_type">
		<xs:sequence>
			<xs:element name="variable" type="named_type" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="output_value_type">
		<xs:sequence>
			<xs:element name="sensor" type="named_type" minOccurs="0"></xs:element>

		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="parameter_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="value" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="route_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="route" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="html_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="path" type="xs:string"></xs:attribute>
		<xs:attribute name="comment" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="webserver_type">
		<xs:sequence>
			<xs:element name="route" type="route_type"></xs:element>
			<xs:element name="html" type="html_type" maxOccurs="unbounded" minOccurs="0"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="adapter_MCP23S17_type">
		<xs:complexContent>
			<xs:extension base="adapter_type">
				<xs:sequence>

					<xs:element name="io" type="mcp23s17:io_type" maxOccurs="unbounded" minOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="adapter_type">
		<xs:sequence>
			<xs:element name="description" type="xs:string" maxOccurs="1" minOccurs="0" />
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="gpio" type="gpio_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="input" type="input_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="input_value" type="input_value_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="output" type="output_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="output_value" type="output_value_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="parameter" type="parameter_type" maxOccurs="unbounded" minOccurs="0">
				</xs:element>
				<xs:element name="webserver" type="webserver_type" maxOccurs="1" minOccurs="0">
				</xs:element>

			</xs:choice>
		</xs:sequence>

		<xs:attribute name="class" type="xs:string"></xs:attribute>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>


	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string" />

				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="adapter" type="adapter_type" />
					<xs:element name="adapter_MCP23S17" type="adapter_MCP23S17_type" />
				</xs:choice>

			</xs:sequence>
			<xs:attribute name="version" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>


	<xs:complexType name="io_type">
		<xs:attribute name="dir" type="iodirection_type"></xs:attribute>
		<xs:attribute name="pull" type="pullup_type"></xs:attribute>
		<xs:attribute name="default" type="default_type"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="iodirection_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="IN"></xs:enumeration>
			<xs:enumeration value="OUT"></xs:enumeration>
			<xs:enumeration value="RESERVED"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="pullup_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="PUD_OFF"></xs:enumeration>
			<xs:enumeration value="PUD_UP"></xs:enumeration>
			<xs:enumeration value="PUD_DOWN"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="named_type">
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:simpleType name="default_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="low"></xs:enumeration>
			<xs:enumeration value="high"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Naohiro2g/scratchClient/config/config_openweatherapi.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0' 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="config.xsd">
       <!--
    # ===========================================================================
    # Copyright (C) 2017  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # ===========================================================================
    -->
    
    <description>Openweather-API interface.</description>

    <!-- =========================================================================== -->

    <adapter class='adapter.openweathermapAdapter.Openweathermap_Adapter' name='openweathermap'>
        <description>Retrieve openweathermap data</description>

        <input_value name='location'>
            <variable name='location' />
        </input_value>
        
        <output_value name='owm_location'>
            <sensor name='owm.location' />
        </output_value>
 
        <output_value name='owm_weather_clouds'>
            <sensor name='owm.clouds' />
        </output_value>
        
        <output_value name='owm_weather_rainfall'>
            <sensor name='owm.rainfall' />
        </output_value>
        
        <output_value name='owm_weather_snowfall'>
            <sensor name='owm.snowfall' />
        </output_value>
        
        <output_value name='owm_weather_temperature'>
            <sensor name='owm.temperature' />
        </output_value>
        
        <output_value name='owm_weather_humidity'>
            <sensor name='owm.humidity' />
        </output_value>
        
        <output_value name='owm_weather_pressure'>
            <sensor name='owm.pressure' />
        </output_value>
        
        <output_value name='owm_weather_wind_speed'>
            <sensor name='owm.wind_speed' />
        </output_value>
        
        <output_value name='owm_weather_wind_direction'>
            <sensor name='owm.wind_direction' />
        </output_value>

        <output_value name='owm_coord_lon'>
            <sensor name='owm.lon' />
        </output_value>
        
        <output_value name='owm_coord_lat'>
            <sensor name='owm.lat' />
        </output_value>

        <output_value name='owm_coord_country'>
            <sensor name='owm.country' />
        </output_value>

       <output_value name='owm_time'>
            <sensor name='owm.time' />
        </output_value>

        <parameter name='openweather.api_key' value='b0d1...' />
        
        <!--  pollrate in seconds
             The api allows pollrate depending on license status. 
             The free API allows pollrates of 10min == 600  -->
             
        <parameter name='pollrate' value='600' />
        
        <!--  default for 'location' -->
        <parameter name='location' value='Leinfelden-Echterdingen' />
        
    </adapter>

</config>

=== Naohiro2g/scratchClient/config/config_remote_0.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2013  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->

	<description>Sample remote communication configuration</description>

	<!-- =========================================================================== -->
	<adapter class='adapter.remote.CommunicationAdapter' name='communication_adapter'>
		
		<!-- Adapter uses native Syntax -->
		
		<description>Remote communication adapter. </description>

        <!--  these commands are received from scratch and forwarded to a remote attached scratchClient -->
		<remote type='forward'>
 		
         	<broadcast name='command_A'/>  
		</remote>

        <!--  these commands are received from a remote attached scratchClient and sent to local scratch -->
		<remote type='receive'>
            <broadcast name='command_B'/>
		</remote>

        <parameter name="group" value="groupA"  />
        <parameter name="server" value="192.168.2.108" />

	</adapter>

    
</config>

=== Naohiro2g/scratchClient/config/config_dht11.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2017  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->
	<description>DHT11, DHT22.</description>

	<!-- =========================================================================== -->
	<adapter class='adapter.pigpiodAdapter.Pigpiod_DHT11_Adapter'  name='dht11'>
		<description>Sample GPIO PWM</description>
		<gpio port='GPIO23'>
			<default dir='IN' pull='PUD_OFF'  />
			<active dir='RESERVED' />
		</gpio>
		
        <output_value name='temperature'>
            <sensor name='temperature'/>
        </output_value>
        <output_value name='humidity'>
            <sensor name='humidity'/>
        </output_value>
        
	</adapter>
	
</config>

=== Naohiro2g/scratchClient/config/config_ikg_rgbpwm_adc_taster.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2014  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->

	<description>
		Arbeitskreis Physical Computing am IKG.
		Ansteuerung einer RGB mit PWM, 2 ADC-Kanテ、le und 1 Taster.
		Die Ansteuerung der LED wird 'rgb_A_R', 'rgb_A_G', 'rgb_A_B' fテシr scratch bezeichnet, 0..100.
		
		Jumper: 
			gesetzt:
			    out.0, 1, 2 gesetzt.
			    in.3 gesetzt.
            offen:
               in.4 bis in.7 
               out2.0 bis out2.7 
        Vorsicht: Frequenz muss immer auf 50 sein !
    </description>
    
	<!-- =========================================================================== -->
	<adapter class='adapter.gpio.GpioOutputPWM'  name='rgb_A_G'>
		<description>RGB_A, GRテ廸</description>

		<gpio port='GPIO25'>
			<default dir='OUT'  default='high' />
			<active  dir='OUT'  default='low' />
		</gpio>
		
		<input_value name='rate'>
			<variable name='rgb_A_G'/>
		</input_value>
		
		<parameter name='frequency' value='50' />
		<parameter name='rate' value='90' />

	</adapter>
	<adapter class='adapter.gpio.GpioOutputPWM'  name='rgb_A_R'>
		<description>RGB_A, ROT</description>

		<gpio port='GPIO24'>
			<default dir='OUT'  default='high' />
			<active  dir='OUT'  default='low' />
		</gpio>
		
		<input_value name='rate'>
			<variable name='rgb_A_R'/>
		</input_value>
		
		<parameter name='frequency' value='50' />
		<parameter name='rate' value='90' />

	</adapter>
	<adapter class='adapter.gpio.GpioOutputPWM'  name='rgb_A_B'>
		<description>RGB_A, Blau</description>

		<gpio port='GPIO23'>
			<default dir='OUT'  default='high' />
			<active  dir='OUT'  default='low' />
		</gpio>
		
		<input_value name='rate'>
			<variable name='rgb_A_B'/>
		</input_value>
		
		<parameter name='frequency' value='50' />
		<parameter name='rate' value='90' />

	</adapter>
    <adapter class='adapter.adc.ADCInput'  name='adc_A'>
        <description>ADC-Value</description>
        <output_value name='adc'>
            <sensor name='adcA'/>
        </output_value>
        <parameter name='poll.interval' value='0.066' />
        <parameter name='spi.bus' value='0' />
        <parameter name='spi.device' value='0' />
        <parameter name='adc.channel' value='0' />
    </adapter>
    
    <adapter class='adapter.adc.ADCInput'  name='adc_B'>
        <description>ADC-Value</description>
        <output_value name='adc'>
            <sensor name='adcB'/>
        </output_value>
        <parameter name='poll.interval' value='0.066' />
        <parameter name='spi.bus' value='0' />
        <parameter name='spi.device' value='0' />
        <parameter name='adc.channel' value='1' />

    </adapter>
    <!-- =========================================================================== -->
    <adapter class='adapter.gpio.GpioEventInput' name='button_s3'>
        
        
        <gpio port='IKG.IO.3'>
            <default dir='IN' pull='PUD_UP'  />
            <active dir='IN' pull='PUD_UP'/>
        </gpio>
        
        <output name='button_pressed'>
            <broadcast name='s3_pressed'/>
        </output>
        <output name='button_released'>
            <broadcast name='s3_released'/>
        </output>
        
        <parameter name='poll.interval' value='0.066' />
        <parameter name='value.inverse' value='true' />

    </adapter>

    <adapter class='adapter.gpio.GpioStateOutput'  name='state'>
        <description>State display on IKG.IO.9</description>

        <gpio port='IKG.IO.9' alias='state'>
            <default dir='OUT'  default='low' />
            <active  dir='OUT'  default='low' />
        </gpio>
    </adapter>

</config>

=== Naohiro2g/scratchClient/config/config_picoBoard.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="config.xsd" >
    <!--
    # ===========================================================================
    # Copyright (C) 2015  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # ===========================================================================
    -->
    <description>Connect Picoboard.
                If you need more than one picoboard, then
                - duplicate the adapter section.
                - rename adapter/@name from 'picoboard' to 'picoboard_0', 'picoboard_1' (or to any unique name you like)
                - rename the adapter/output_value/sensor/@name values to unique names to make these separate for each adapter.
                  e.g. adapter/output_value/sensor[@name='slider'] [1] /@name to  slider_0
                       adapter/output_value/sensor[@name='slider'] [2] /@name to  slider_1
                 - rename parameter/ @name='serial.device' to match each picoboard, most probably /dev/ttyUSB0, /dev/ttyUSB1
                </description>

    <!-- =========================================================================== -->
    <adapter class='adapter.serialAdapter.PicoBoard_Adapter'  name='picoboard'>
        <description>ScratchBoard, picoboard adapter</description>
        
        <output_value name='slider'>
            <sensor name='slider'/>
        </output_value>
        
        <output_value name='light'>
            <sensor name='light'/>
        </output_value>
        
        <output_value name='sound'>
            <sensor name='sound'/>
        </output_value>
        
        <output_value name='button'>
            <sensor name='button'/>
        </output_value>
        
        <output_value name='sensorA'>
            <sensor name='resistance-A'/>
        </output_value>
        
        <output_value name='sensorB'>
            <sensor name='resistance-B'/>
        </output_value>
        
        <output_value name='sensorC'>
            <sensor name='resistance-C'/>
        </output_value>
        
        <output_value name='sensorD'>
            <sensor name='resistance-D'/>
        </output_value>
        
        <parameter name='serial.device' value='/dev/ttyUSB0' />
        <parameter name='serial.baud' value='38400' />

        <parameter name='picoBoard.raw' value='false' />
       
    </adapter>

</config>

=== Naohiro2g/scratchClient/scratch/pianoHat/config_pianohat.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0'
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="config.xsd" >
	<!--
	# ===========================================================================
	# Copyright (C) 2013  Gerhard Hepp
	#
	# This program is free software; you can redistribute it and/or modify it under the terms of
	# the GNU General Public License as published by the Free Software Foundation; either version 2
	# of the License, or (at your option) any later version.
	#
	# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
	# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	# See the GNU General Public License for more details.
	#
	# You should have received a copy of the GNU General Public License along with this program; if
	# not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
	# MA 02110, USA
	# ===========================================================================
	-->

	<description>Sample configuration</description>

	<!-- =========================================================================== -->
	<adapter class='adapter.Cap1188Adapter.PianoHat_CAP1188_Adapter' name='piano_adapter'>
		
		<description>pimoroni piano hat</description>
	

        <output name='broadcast_00_on'><broadcast name='button_00'/></output>
        <output name='broadcast_01_on'><broadcast name='button_01'/></output>
        <output name='broadcast_02_on'><broadcast name='button_02'/></output>
        <output name='broadcast_03_on'><broadcast name='button_03'/></output>
        <output name='broadcast_04_on'><broadcast name='button_04'/></output>
        <output name='broadcast_05_on'><broadcast name='button_05'/></output>
        <output name='broadcast_06_on'><broadcast name='button_06'/></output>
        <output name='broadcast_07_on'><broadcast name='button_07'/></output>
        <output name='broadcast_08_on'><broadcast name='button_08'/></output>
        <output name='broadcast_09_on'><broadcast name='button_09'/></output>
        <output name='broadcast_10_on'><broadcast name='button_10'/></output>
        <output name='broadcast_11_on'><broadcast name='button_11'/></output>
        <output name='broadcast_12_on'><broadcast name='button_12'/></output>
        <output name='broadcast_13_on'><broadcast name='button_13'/></output>
        <output name='broadcast_14_on'><broadcast name='button_14'/></output>
        <output name='broadcast_15_on'><broadcast name='button_15'/></output>

        <output name='broadcast_00_off'><broadcast name='button_00_off'/></output>
        <output name='broadcast_01_off'><broadcast name='button_01_off'/></output>
        <output name='broadcast_02_off'><broadcast name='button_02_off'/></output>
        <output name='broadcast_03_off'><broadcast name='button_03_off'/></output>
        <output name='broadcast_04_off'><broadcast name='button_04_off'/></output>
        <output name='broadcast_05_off'><broadcast name='button_05_off'/></output>
        <output name='broadcast_06_off'><broadcast name='button_06_off'/></output>
        <output name='broadcast_07_off'><broadcast name='button_07_off'/></output>
        <output name='broadcast_08_off'><broadcast name='button_08_off'/></output>
        <output name='broadcast_09_off'><broadcast name='button_09_off'/></output>
        <output name='broadcast_10_off'><broadcast name='button_10_off'/></output>
        <output name='broadcast_11_off'><broadcast name='button_11_off'/></output>
        <output name='broadcast_12_off'><broadcast name='button_12_off'/></output>
        <output name='broadcast_13_off'><broadcast name='button_13_off'/></output>
        <output name='broadcast_14_off'><broadcast name='button_14_off'/></output>
        <output name='broadcast_15_off'><broadcast name='button_15_off'/></output>

        <parameter name="auto_leds" value="true"  />

	</adapter>

</config>

=== Naohiro2g/scratchClient/config/config_mcp23s17.xml
<?xml version='1.0' encoding='utf-8' ?>
<config version='1.0' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:mcp23s17="mcp23s17.xsd" xsi:noNamespaceSchemaLocation="config.xsd"
	xsi:schemaLocation="mcp23s17 mcp23s17.xsd "
>

	<!-- 
    # =============================================================================================
    # Copyright (C) 2013  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # =============================================================================================
		-->

	<description>
		Sample MCP23S17; this configuration is suitable to be used with PIFACE board.
        When using piFace, then do NOT use GPIO25 (this is INTB in MCP23S17) 
    </description>

	<!-- =========================================================================== -->
	<adapter class='adapter.mcp23s17.MCP23S17_Adapter' name='MCP23S17'>
		<!-- no description, urgg -->

		<!-- input_value methods in python are dynamically generated like inputGPA4 for io@dir=out -->

		<input_value name='inputGPA0'>
			<variable name='out_0' />
			<variable name='relais_0' />
			<variable name='all' />

		</input_value>
		<input_value name='inputGPA1'>
			<variable name='out_1' />
			<variable name='relais_1' />
			<variable name='all' />
		</input_value>
		<input_value name='inputGPA2'>
		
		 
            <variable name='out_2' />
        	<variable name='all' />

		</input_value>
		<input_value name='inputGPA3'>
		   
			<variable name='out_3' />
			<variable name='all' />

		</input_value>

		<input_value name='inputGPA4'>
			<variable name='out_4' />
			<variable name='all' />

		</input_value>
		<input_value name='inputGPA5'>
			<variable name='out_5' />
			<variable name='all' />

		</input_value>
		<input_value name='inputGPA6'>
			<variable name='out_6' />
			<variable name='all' />

		</input_value>
		<input_value name='inputGPA7'>
			<variable name='out_7' />
			<variable name='all' />

		</input_value>

		<!-- output_value methods in python are dynamically generated like outputGPB2 for io@dir=in -->

		<output_value name='outputGPB0'>
			<sensor name='in_0' />
		</output_value>

		<output_value name='outputGPB1'>
			<sensor name='in_1' />
		</output_value>

		<output_value name='outputGPB2'>
			<sensor name='in_2' />
		</output_value>

		<output_value name='outputGPB3'>
			<sensor name='in_3' />
		</output_value>

		<output_value name='outputGPB4'>
			<sensor name='in_4' />
		</output_value>

		<output_value name='outputGPB5'>
			<sensor name='in_5' />
		</output_value>

		<output_value name='outputGPB6'>
			<sensor name='in_6' />
		</output_value>

		<output_value name='outputGPB7'>
			<sensor name='in_7' />
		</output_value>

		<parameter name='poll.interval' value='0.05' />

		<parameter name='spi.bus' value='0' />
		<parameter name='spi.device' value='0' />
		<!-- slave address must match the hard wired slave address on the device -->
		<parameter name='23s17.addr' value='0' />

		<!-- this is the setup for piface -->
		
		<io id='GPA0' dir='out' />
		<io id='GPA1' dir='out' />
		<io id='GPA2' dir='out' />
		<io id='GPA3' dir='out' />

		<io id='GPA4' dir='out' />
		<io id='GPA5' dir='out' />
		<io id='GPA6' dir='out' />
		<io id='GPA7' dir='out' />

		<io id='GPB0' dir='in' pullup='weak' />
		<io id='GPB1' dir='in' pullup='weak' />
		<io id='GPB2' dir='in' pullup='weak' />
		<io id='GPB3' dir='in' pullup='weak' />

		<io id='GPB4' dir='in' pullup='weak' />
		<io id='GPB5' dir='in' pullup='weak' />
		<io id='GPB6' dir='in' pullup='weak' />
		<io id='GPB7' dir='in' pullup='weak' />

	</adapter>

</config>
