=== Naohiro2g/scratchClient/config/portMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="port_type">
		<xs:attribute name="gpioNumber" type="xs:int"></xs:attribute>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:element name="portMapping">
        <xs:complexType>
			<xs:sequence>
    			<xs:element name="port" type="port_type" maxOccurs="unbounded" minOccurs="1" />
			</xs:sequence>
			<xs:attribute name="version" type="xs:string"></xs:attribute>
		</xs:complexType>
    </xs:element>

</xs:schema>

=== Naohiro2g/scratchClient/config/portMapping.xml
<?xml version='1.0' encoding='utf-8' ?>

<portMapping version='1.0'
xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
xsi:noNamespaceSchemaLocation='portMapping.xsd' >
    <!--
    # ===========================================================================
    # Copyright (C) 2013  Gerhard Hepp
    #
    # This program is free software; you can redistribute it and/or modify it under the terms of
    # the GNU General Public License as published by the Free Software Foundation; either version 2
    # of the License, or (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
    # without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    # See the GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License along with this program; if
    # not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
    # MA 02110, USA
    # ===========================================================================
    -->
    
    <!--  GPIO Names. Not all of these are mapped to a header -->
    
    <port gpioNumber='0' name='GPIO00' />
    <port gpioNumber='1' name='GPIO01' />
    <port gpioNumber='2' name='GPIO02' />
    <port gpioNumber='3' name='GPIO03' />
    <port gpioNumber='4' name='GPIO04' />
    <port gpioNumber='5' name='GPIO05' />
    <port gpioNumber='6' name='GPIO06' />
    <port gpioNumber='7' name='GPIO07' />
    <port gpioNumber='8' name='GPIO08' />
    <port gpioNumber='9' name='GPIO09' />
    <port gpioNumber='10' name='GPIO10' />
    <port gpioNumber='11' name='GPIO11' />
    <port gpioNumber='12' name='GPIO12' />
    <port gpioNumber='13' name='GPIO13' />
    <port gpioNumber='14' name='GPIO14' />
    <port gpioNumber='15' name='GPIO15' />
    <port gpioNumber='16' name='GPIO16' />
    <port gpioNumber='17' name='GPIO17' />
    <port gpioNumber='18' name='GPIO18' />
    <port gpioNumber='19' name='GPIO19' />
    <port gpioNumber='20' name='GPIO20' />
    <port gpioNumber='21' name='GPIO21' />
    <port gpioNumber='22' name='GPIO22' />
    <port gpioNumber='23' name='GPIO23' />
    <port gpioNumber='24' name='GPIO24' />
    <port gpioNumber='25' name='GPIO25' />
    <port gpioNumber='26' name='GPIO26' />
    <port gpioNumber='27' name='GPIO27' />
    <port gpioNumber='28' name='GPIO28' />
    <port gpioNumber='29' name='GPIO29' />
    <port gpioNumber='30' name='GPIO30' />
    <port gpioNumber='31' name='GPIO31' />
    
    <!--  Port names for IKG-Adapter board -->
    <port gpioNumber='25' name='IKG.IO.0' />
    <port gpioNumber='24' name='IKG.IO.1' />
    <port gpioNumber='23' name='IKG.IO.2' />
    <port gpioNumber='18' name='IKG.IO.3' />
    <port gpioNumber='22' name='IKG.IO.4' />
    <port gpioNumber='27' name='IKG.IO.5' />
    <port gpioNumber='17' name='IKG.IO.6' />
    <port gpioNumber='15' name='IKG.IO.7' />
    <port gpioNumber='14' name='IKG.IO.8' description="button s8" />
    <port gpioNumber='4' name='IKG.IO.9' description="LED 9"/>
    
    <!--  Port names for Raspberry Pi Pin numbers  -->
    <port gpioNumber='0' name='P1-03V1' />
    <port gpioNumber='1' name='P1-05V1' />
    <port gpioNumber='2' name='P1-03V2' />
    <port gpioNumber='3' name='P1-05V2' />
    <port gpioNumber='4' name='P1-07' />
    <port gpioNumber='7' name='P1-26' />
    <port gpioNumber='8' name='P1-24' />
    <port gpioNumber='9' name='P1-21' />
    <port gpioNumber='10' name='P1-19' />
    <port gpioNumber='11' name='P1-23' />
    <port gpioNumber='14' name='P1-08' />
    <port gpioNumber='15' name='P1-10' />
    <port gpioNumber='17' name='P1-11' />
    <port gpioNumber='18' name='P1-12' />
    <port gpioNumber='21' name='P1-13V1' />
    <port gpioNumber='27' name='P1-13V2' />
    <port gpioNumber='22' name='P1-15' />
    <port gpioNumber='23' name='P1-16' />
    <port gpioNumber='24' name='P1-18' />
    <port gpioNumber='25' name='P1-22' />
    <port gpioNumber='28' name='P3-03' />
    <port gpioNumber='29' name='P3-04' />
    <port gpioNumber='30' name='P3-05' />
    <port gpioNumber='31' name='P3-06' />

     <!-- P3B, PZW, PZ, P2B, P1B+, P1A+ -->
    <port gpioNumber='0' name='PIN27'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='1' name='PIN28'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='2' name='PIN03'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='3' name='PIN05'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='4' name='PIN07'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='5' name='PIN29'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='6' name='PIN31'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='7' name='PIN26'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='8' name='PIN24'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='9' name='PIN21'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='10' name='PIN19'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='11' name='PIN23'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='12' name='PIN32'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='13' name='PIN33'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='14' name='PIN08'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='15' name='PIN10'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='16' name='PIN36'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='17' name='PIN11'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='18' name='PIN12'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='19' name='PIN35'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='20' name='PIN38'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='21' name='PIN40'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='22' name='PIN15'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='23' name='PIN16'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='24' name='PIN18'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='25' name='PIN22'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='26' name='PIN37'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='27' name='PIN13'  version="P3B, PZW, PZ, P2B, P1B+, P1A+" />
    <port gpioNumber='28' name='GPIO28' />
    <port gpioNumber='29' name='GPIO29' />
    <port gpioNumber='30' name='GPIO30' />
    <port gpioNumber='31' name='GPIO31' />


</portMapping>
